services:
  auth-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017/auth_db
      - REDIS_URI=redis:6379
      - RSA_PRIVATE_KEY=/app/keys/id_rs256
      - RSA_PUBLIC_KEY=/app/keys/id_rs256.pub
      - ISSUER=http://localhost:8080
    volumes:
      - ./keys:/app/keys
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
