// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: api/proto/options/v1/auth_rule.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles       []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	AllowAny    bool     `protobuf:"varint,3,opt,name=allow_any,json=allowAny,proto3" json:"allow_any,omitempty"`
}

func (x *AuthRule) Reset() {
	*x = AuthRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_options_v1_auth_rule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRule) ProtoMessage() {}

func (x *AuthRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_options_v1_auth_rule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRule.ProtoReflect.Descriptor instead.
func (*AuthRule) Descriptor() ([]byte, []int) {
	return file_api_proto_options_v1_auth_rule_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRule) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AuthRule) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AuthRule) GetAllowAny() bool {
	if x != nil {
		return x.AllowAny
	}
	return false
}

var file_api_proto_options_v1_auth_rule_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthRule)(nil),
		Field:         50000,
		Name:          "options.v1.rule",
		Tag:           "bytes,50000,opt,name=rule",
		Filename:      "api/proto/options/v1/auth_rule.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional options.v1.AuthRule rule = 50000;
	E_Rule = &file_api_proto_options_v1_auth_rule_proto_extTypes[0]
)

var File_api_proto_options_v1_auth_rule_proto protoreflect.FileDescriptor

var file_api_proto_options_v1_auth_rule_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x75, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x52, 0x75, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x61, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x41, 0x6e, 0x79, 0x3a, 0x4a, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x12, 0x1e, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x75, 0x6c,
	0x65, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x71, 0x75, 0x61, 0x6c, 0x6c, 0x2d, 0x63, 0x68, 0x75, 0x61, 0x2f, 0x67, 0x6f, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2d, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_options_v1_auth_rule_proto_rawDescOnce sync.Once
	file_api_proto_options_v1_auth_rule_proto_rawDescData = file_api_proto_options_v1_auth_rule_proto_rawDesc
)

func file_api_proto_options_v1_auth_rule_proto_rawDescGZIP() []byte {
	file_api_proto_options_v1_auth_rule_proto_rawDescOnce.Do(func() {
		file_api_proto_options_v1_auth_rule_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_options_v1_auth_rule_proto_rawDescData)
	})
	return file_api_proto_options_v1_auth_rule_proto_rawDescData
}

var file_api_proto_options_v1_auth_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_options_v1_auth_rule_proto_goTypes = []interface{}{
	(*AuthRule)(nil),                   // 0: options.v1.AuthRule
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_api_proto_options_v1_auth_rule_proto_depIdxs = []int32{
	1, // 0: options.v1.rule:extendee -> google.protobuf.MethodOptions
	0, // 1: options.v1.rule:type_name -> options.v1.AuthRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_options_v1_auth_rule_proto_init() }
func file_api_proto_options_v1_auth_rule_proto_init() {
	if File_api_proto_options_v1_auth_rule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_options_v1_auth_rule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_options_v1_auth_rule_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_options_v1_auth_rule_proto_goTypes,
		DependencyIndexes: file_api_proto_options_v1_auth_rule_proto_depIdxs,
		MessageInfos:      file_api_proto_options_v1_auth_rule_proto_msgTypes,
		ExtensionInfos:    file_api_proto_options_v1_auth_rule_proto_extTypes,
	}.Build()
	File_api_proto_options_v1_auth_rule_proto = out.File
	file_api_proto_options_v1_auth_rule_proto_rawDesc = nil
	file_api_proto_options_v1_auth_rule_proto_goTypes = nil
	file_api_proto_options_v1_auth_rule_proto_depIdxs = nil
}
