// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/proto/admin/v1/oidcclient.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OIDCClientService_RegisterClient_FullMethodName     = "/admin.v1.OIDCClientService/RegisterClient"
	OIDCClientService_GetClient_FullMethodName          = "/admin.v1.OIDCClientService/GetClient"
	OIDCClientService_UpdateClient_FullMethodName       = "/admin.v1.OIDCClientService/UpdateClient"
	OIDCClientService_DeleteClient_FullMethodName       = "/admin.v1.OIDCClientService/DeleteClient"
	OIDCClientService_ListClients_FullMethodName        = "/admin.v1.OIDCClientService/ListClients"
	OIDCClientService_RotateClientSecret_FullMethodName = "/admin.v1.OIDCClientService/RotateClientSecret"
)

// OIDCClientServiceClient is the client API for OIDCClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OIDCClientServiceClient interface {
	RegisterClient(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*OIDCClient, error)
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*OIDCClient, error)
	UpdateClient(ctx context.Context, in *UpdateClientRequest, opts ...grpc.CallOption) (*OIDCClient, error)
	DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
	RotateClientSecret(ctx context.Context, in *RotateClientSecretRequest, opts ...grpc.CallOption) (*RotateClientSecretResponse, error)
}

type oIDCClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOIDCClientServiceClient(cc grpc.ClientConnInterface) OIDCClientServiceClient {
	return &oIDCClientServiceClient{cc}
}

func (c *oIDCClientServiceClient) RegisterClient(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*OIDCClient, error) {
	out := new(OIDCClient)
	err := c.cc.Invoke(ctx, OIDCClientService_RegisterClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oIDCClientServiceClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*OIDCClient, error) {
	out := new(OIDCClient)
	err := c.cc.Invoke(ctx, OIDCClientService_GetClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oIDCClientServiceClient) UpdateClient(ctx context.Context, in *UpdateClientRequest, opts ...grpc.CallOption) (*OIDCClient, error) {
	out := new(OIDCClient)
	err := c.cc.Invoke(ctx, OIDCClientService_UpdateClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oIDCClientServiceClient) DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OIDCClientService_DeleteClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oIDCClientServiceClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, OIDCClientService_ListClients_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oIDCClientServiceClient) RotateClientSecret(ctx context.Context, in *RotateClientSecretRequest, opts ...grpc.CallOption) (*RotateClientSecretResponse, error) {
	out := new(RotateClientSecretResponse)
	err := c.cc.Invoke(ctx, OIDCClientService_RotateClientSecret_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OIDCClientServiceServer is the server API for OIDCClientService service.
// All implementations should embed UnimplementedOIDCClientServiceServer
// for forward compatibility
type OIDCClientServiceServer interface {
	RegisterClient(context.Context, *RegisterClientRequest) (*OIDCClient, error)
	GetClient(context.Context, *GetClientRequest) (*OIDCClient, error)
	UpdateClient(context.Context, *UpdateClientRequest) (*OIDCClient, error)
	DeleteClient(context.Context, *DeleteClientRequest) (*emptypb.Empty, error)
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	RotateClientSecret(context.Context, *RotateClientSecretRequest) (*RotateClientSecretResponse, error)
}

// UnimplementedOIDCClientServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOIDCClientServiceServer struct {
}

func (UnimplementedOIDCClientServiceServer) RegisterClient(context.Context, *RegisterClientRequest) (*OIDCClient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedOIDCClientServiceServer) GetClient(context.Context, *GetClientRequest) (*OIDCClient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedOIDCClientServiceServer) UpdateClient(context.Context, *UpdateClientRequest) (*OIDCClient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClient not implemented")
}
func (UnimplementedOIDCClientServiceServer) DeleteClient(context.Context, *DeleteClientRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClient not implemented")
}
func (UnimplementedOIDCClientServiceServer) ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedOIDCClientServiceServer) RotateClientSecret(context.Context, *RotateClientSecretRequest) (*RotateClientSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateClientSecret not implemented")
}

// UnsafeOIDCClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OIDCClientServiceServer will
// result in compilation errors.
type UnsafeOIDCClientServiceServer interface {
	mustEmbedUnimplementedOIDCClientServiceServer()
}

func RegisterOIDCClientServiceServer(s grpc.ServiceRegistrar, srv OIDCClientServiceServer) {
	s.RegisterService(&OIDCClientService_ServiceDesc, srv)
}

func _OIDCClientService_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCClientServiceServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCClientService_RegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCClientServiceServer).RegisterClient(ctx, req.(*RegisterClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OIDCClientService_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCClientServiceServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCClientService_GetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCClientServiceServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OIDCClientService_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCClientServiceServer).UpdateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCClientService_UpdateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCClientServiceServer).UpdateClient(ctx, req.(*UpdateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OIDCClientService_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCClientServiceServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCClientService_DeleteClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCClientServiceServer).DeleteClient(ctx, req.(*DeleteClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OIDCClientService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCClientServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCClientService_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCClientServiceServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OIDCClientService_RotateClientSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateClientSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCClientServiceServer).RotateClientSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCClientService_RotateClientSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCClientServiceServer).RotateClientSecret(ctx, req.(*RotateClientSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OIDCClientService_ServiceDesc is the grpc.ServiceDesc for OIDCClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OIDCClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.OIDCClientService",
	HandlerType: (*OIDCClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterClient",
			Handler:    _OIDCClientService_RegisterClient_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _OIDCClientService_GetClient_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _OIDCClientService_UpdateClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _OIDCClientService_DeleteClient_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _OIDCClientService_ListClients_Handler,
		},
		{
			MethodName: "RotateClientSecret",
			Handler:    _OIDCClientService_RotateClientSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/admin/v1/oidcclient.proto",
}
