// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/proto/auth/v1/web3.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Web3AuthService_RequestNonce_FullMethodName = "/auth.v1.Web3AuthService/RequestNonce"
	Web3AuthService_Verify_FullMethodName       = "/auth.v1.Web3AuthService/Verify"
	Web3AuthService_ListWallets_FullMethodName  = "/auth.v1.Web3AuthService/ListWallets"
	Web3AuthService_LinkWallet_FullMethodName   = "/auth.v1.Web3AuthService/LinkWallet"
	Web3AuthService_UnlinkWallet_FullMethodName = "/auth.v1.Web3AuthService/UnlinkWallet"
)

// Web3AuthServiceClient is the client API for Web3AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Web3AuthServiceClient interface {
	RequestNonce(ctx context.Context, in *RequestNonceRequest, opts ...grpc.CallOption) (*RequestNonceResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*TokenPair, error)
	ListWallets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWalletsResponse, error)
	LinkWallet(ctx context.Context, in *LinkWalletRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnlinkWallet(ctx context.Context, in *UnlinkWalletRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type web3AuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeb3AuthServiceClient(cc grpc.ClientConnInterface) Web3AuthServiceClient {
	return &web3AuthServiceClient{cc}
}

func (c *web3AuthServiceClient) RequestNonce(ctx context.Context, in *RequestNonceRequest, opts ...grpc.CallOption) (*RequestNonceResponse, error) {
	out := new(RequestNonceResponse)
	err := c.cc.Invoke(ctx, Web3AuthService_RequestNonce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *web3AuthServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	out := new(TokenPair)
	err := c.cc.Invoke(ctx, Web3AuthService_Verify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *web3AuthServiceClient) ListWallets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWalletsResponse, error) {
	out := new(ListWalletsResponse)
	err := c.cc.Invoke(ctx, Web3AuthService_ListWallets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *web3AuthServiceClient) LinkWallet(ctx context.Context, in *LinkWalletRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Web3AuthService_LinkWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *web3AuthServiceClient) UnlinkWallet(ctx context.Context, in *UnlinkWalletRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Web3AuthService_UnlinkWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Web3AuthServiceServer is the server API for Web3AuthService service.
// All implementations should embed UnimplementedWeb3AuthServiceServer
// for forward compatibility
type Web3AuthServiceServer interface {
	RequestNonce(context.Context, *RequestNonceRequest) (*RequestNonceResponse, error)
	Verify(context.Context, *VerifyRequest) (*TokenPair, error)
	ListWallets(context.Context, *emptypb.Empty) (*ListWalletsResponse, error)
	LinkWallet(context.Context, *LinkWalletRequest) (*emptypb.Empty, error)
	UnlinkWallet(context.Context, *UnlinkWalletRequest) (*emptypb.Empty, error)
}

// UnimplementedWeb3AuthServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWeb3AuthServiceServer struct {
}

func (UnimplementedWeb3AuthServiceServer) RequestNonce(context.Context, *RequestNonceRequest) (*RequestNonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestNonce not implemented")
}
func (UnimplementedWeb3AuthServiceServer) Verify(context.Context, *VerifyRequest) (*TokenPair, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedWeb3AuthServiceServer) ListWallets(context.Context, *emptypb.Empty) (*ListWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWallets not implemented")
}
func (UnimplementedWeb3AuthServiceServer) LinkWallet(context.Context, *LinkWalletRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkWallet not implemented")
}
func (UnimplementedWeb3AuthServiceServer) UnlinkWallet(context.Context, *UnlinkWalletRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkWallet not implemented")
}

// UnsafeWeb3AuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Web3AuthServiceServer will
// result in compilation errors.
type UnsafeWeb3AuthServiceServer interface {
	mustEmbedUnimplementedWeb3AuthServiceServer()
}

func RegisterWeb3AuthServiceServer(s grpc.ServiceRegistrar, srv Web3AuthServiceServer) {
	s.RegisterService(&Web3AuthService_ServiceDesc, srv)
}

func _Web3AuthService_RequestNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Web3AuthServiceServer).RequestNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web3AuthService_RequestNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Web3AuthServiceServer).RequestNonce(ctx, req.(*RequestNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web3AuthService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Web3AuthServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web3AuthService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Web3AuthServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web3AuthService_ListWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Web3AuthServiceServer).ListWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web3AuthService_ListWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Web3AuthServiceServer).ListWallets(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web3AuthService_LinkWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Web3AuthServiceServer).LinkWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web3AuthService_LinkWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Web3AuthServiceServer).LinkWallet(ctx, req.(*LinkWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web3AuthService_UnlinkWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Web3AuthServiceServer).UnlinkWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web3AuthService_UnlinkWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Web3AuthServiceServer).UnlinkWallet(ctx, req.(*UnlinkWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Web3AuthService_ServiceDesc is the grpc.ServiceDesc for Web3AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Web3AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.Web3AuthService",
	HandlerType: (*Web3AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestNonce",
			Handler:    _Web3AuthService_RequestNonce_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Web3AuthService_Verify_Handler,
		},
		{
			MethodName: "ListWallets",
			Handler:    _Web3AuthService_ListWallets_Handler,
		},
		{
			MethodName: "LinkWallet",
			Handler:    _Web3AuthService_LinkWallet_Handler,
		},
		{
			MethodName: "UnlinkWallet",
			Handler:    _Web3AuthService_UnlinkWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/auth/v1/web3.proto",
}
